channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - nbgitpuller
  - r-base=4 # R dependencies
  - bioconductor-ggtree=3.2
  - bioconductor-microbiome=1.10
  - r-ape=5.4_1
  - r-useful
  - r-broom=0.7
  - r-dplyr=1.0
  - r-ggplot2=3.3
  - r-pheatmap=1.0
  - r-ggbeeswarm>=0.6
  - r-phytools=0.7_47
  - r-plotly=4.9.2
  - r-purrr=0.3
  - r-readr=1.3
  - r-stringr=1.4
  - r-tibble=3.0
  - r-tidyr=1.1
  - r-vegan=2.5_6
  - r-kableextra=1.2
  - bioconductor-aldex2=1.20
  - r-heatmaply=1.3
