channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - nbgitpuller
  - r-base=4.1 # R dependencies
  - bioconductor-ggtree=3.0
  - bioconductor-microbiome=1.14
  - r-useful=1.2
  - r-ape=5.5
  - r-broom=0.7
  - r-dplyr=1.0
  - r-ggplot2=3.3
  - r-pheatmap=1.0
  - r-phytools=0.7
  - r-plotly=4.9.4
  - r-purrr=0.3
  - r-readr=2.0
  - r-stringr=1.4
  - r-tibble=3.1
  - r-tidyr=1.1
  - r-vegan=2.5
  - r-kableextra=1.3
  - bioconductor-aldex2=1.24
