channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - nbgitpuller
# binder builds with r-irkernel=1.10.2021
  - r-base # R dependencies
  - bioconductor-ggtree
  - bioconductor-microbiome
  - r-useful
  - r-ape
  - r-broom
  - r-dplyr
  - r-ggplot2
  - r-pheatmap
  - r-phytools
  - r-plotly
  - r-purrr
  - r-readr
  - r-stringr
  - r-tibble
  - r-tidyr
  - r-vegan
  - r-kableextra
  - bioconductor-aldex2
