channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - nbgitpuller
  - python=3.9
  - pandas=1.2
  - matplotlib>=3.1
  - seaborn>=0.10
  - jupyterlab>=2.2
  - altair>=4.1
  - scikit-bio>=0.5.5
  - scikit-learn>=0.21.3
  - ete3
