channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - nbgitpuller
  - r-base=4 # R dependencies
  - bioconductor-ggtree
  - bioconductor-microbiome
  - r-ape=5
  - r-useful
  - r-broom
  - r-dplyr
  - r-ggplot2=3
  - r-pheatmap=1
  - r-ggbeeswarm
  - r-phytools
  - r-plotly
  - r-purrr
  - r-readr
  - r-stringr
  - r-tibble=3
  - r-tidyr
  - r-vegan=2
  - r-kableextra=1
  - bioconductor-aldex2=1
  - r-heatmaply
